name = "donut-clicker"
main = "functions/index.js"
compatibility_date = "2024-05-20"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Leaderboard"]

[assets]
directory = "./public"

[durable_objects]
bindings = [
  { name = "LEADERBOARD", class_name = "Leaderboard" }
] 